[variables]
COMPOSER_ALLOW_SUPERUSER = "1"

[phases.setup]
nixPackages = [
    "php83", 
    "php83Extensions.pdo", 
    "php83Extensions.pdo_pgsql", 
    "php83Extensions.gd",
    "php83Extensions.zip",
    "php83Extensions.mbstring",
    "nodejs_20"
]

[phases.build]
cmds = [
    "composer update --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install",
    "npm run build"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"